### ISSUE TITLE
Very little speed improvement

### ISSUE THREAD

**Issue by leoliu0** [talboger/fastdist#10]
I have experimented with cosine pairwise distance with a matrix of shape (10000,700). It seems like we have little improvement of speed.

%%time
res = fastdist.cosine_pairwise_distance(x[:10000])
CPU times: user 14.9 s, sys: 290 ms, total: 15.2 s
Wall time: 15.2 s

%%time
res = pdist(x[:10000],'cosine')
CPU times: user 17.9 s, sys: 46.7 ms, total: 18 s
Wall time: 18 s

Is there any chance of improving the speed?

**Comment by talboger** [comment]
Sorry about that. fastdist is still faster here; while fastdist is generally faster than scipy.spatial.distance, some functions have larger speed differences than others. I've played around with the code in an attempt to increase speed more and have not yet been able to find something.
