### ISSUE TITLE
The provided matrices are being modified inplace for cosine matrix to matrix distance computation

### ISSUE THREAD

**Issue by 100rab-S** [talboger/fastdist#16]
Hi @talboger 
The matrices provided to the function `def matrix_to_matrix_distance()`  with 'cosine' as the distance metric is getting modified inplace.

**Comment by talboger** [comment]
good catch, fixed in https://github.com/talboger/fastdist/commit/a7f21b86f81acfbae7bf94c6a4d105ab0744efeb
