### ISSUE TITLE
Hamming distance is slow?

### ISSUE THREAD

**Issue by iraykhel** [talboger/fastdist#17]
Calculating the hamming distance between two integer matrices is about 5 times slower with fastdist than with cdist. Matrix size is about 10K rows, 10 columns. cdist takes 3 seconds, fastdist takes 15

**Comment by talboger** [comment]
sorry about that. i just checked this at various matrix sizes, and it seems you are right; in most cases, fastdist appears to be slower than cdist for hamming distance. i will look into how to further optimize the fastdist version of the computation in the next release!
