### ISSUE TITLE
fastdist matrix_to_matrix_distance is several times slower than scipy cdist

### ISSUE THREAD

**Issue by ogencoglu** [talboger/fastdist#21]
Here is a en example:

```
np.random.seed(42)
array1 = np.random.rand(1106, 2)
array2 = np.random.rand(422, 2)

%timeit -n 30 -r 3 cdist(array1, array2, metric="euclidean")  # 795 μs ± 203 μs per loop (mean ± std. dev. of 3 runs, 30 loops each)
%timeit -n 30 -r 3 fastdist.matrix_to_matrix_distance(array1, array2, fastdist.euclidean, "euclidean")  # 27.8 ms ± 5.65 ms per loop (mean ± std. dev. of 3 runs, 30 loops each)
```

System: Mac
Python: 3.12
scipy version: 1.4.1
numba version: 0.60.0
fastdist version: 1.1.6

**Comment by talboger** [comment]
thank you for raising this. as has been observed in other issues, it is not _always_ the case that fastdist is faster that scipy.spatial.distance. indeed, there are some cases where it is slower, especially if you include the compiling run in the timing. 

in general, for larger arrays and for certain functions (e.g., cosine distance, confusion matrix-based functions), fastdist is faster than alternatives. when that is not the case, as you have found here, one can test the speed of alternatives and decide which to use.

**Comment by ogencoglu** [comment]
Thanks for the swift reply. I implemented pure numba based cdist for this use case and it does the job. Appreciate this library nevertheless.
