### ISSUE TITLE
fastdist does not wotk with python3.9 + numba 0.51.2 + numpy 1.19.4

### ISSUE THREAD

**Issue by j-musial** [talboger/fastdist#3]
Hello,

When I call examples from the fastdist I get the following errors:

from fastdist import fastdist
import numpy as np
a = np.random.rand(10, 100)
fastdist.matrix_pairwise_distance(a, fastdist.euclidean, "euclidean", return_matrix=False)

TypingError                               Traceback (most recent call last)
<ipython-input-2-2a4d20d065b4> in <module>
      3 
      4 a = np.random.rand(10, 100)
----> 5 fastdist.matrix_pairwise_distance(a, fastdist.euclidean, "euclidean", return_matrix=False)

/opt/venv/python3.9/lib/python3.9/site-packages/numba/core/dispatcher.py in _compile_for_args(self, *args, **kws)
    413                 e.patch_message(msg)
    414 
--> 415             error_rewrite(e, 'typing')
    416         except errors.UnsupportedError as e:
    417             # Something unsupported is present in the user code, add help info

/opt/venv/python3.9/lib/python3.9/site-packages/numba/core/dispatcher.py in error_rewrite(e, issue_type)
    356                 raise e
    357             else:
--> 358                 reraise(type(e), e, None)
    359 
    360         argtypes = []

/opt/venv/python3.9/lib/python3.9/site-packages/numba/core/utils.py in reraise(tp, value, tb)
     78         value = tp()
     79     if value.__traceback__ is not tb:
---> 80         raise value.with_traceback(tb)
     81     raise value
     82 

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function arange>) found for signature:
 
 >>> arange(int64)
 
There are 2 candidate implementations:
   - Of which 2 did not match due to:
   Overload in function 'np_arange': File: numba/np/arrayobj.py: Line 3842.
     With argument(s): '(int64)':
    Rejected as the implementation raised a specific error:
      UnsupportedError: Failed in nopython mode pipeline (step: analyzing bytecode)
    Use of unsupported opcode (IS_OP) found
    
    File "../../opt/venv/python3.9/lib/python3.9/site-packages/numba/np/arrayobj.py", line 3879:
        def impl(start, stop=None, step=None, dtype=None):
            <source elided>
            # Allow for improved performance if given literal arguments.
            lit_start = start_value if start_value is not None else start
            ^

  raised from /opt/venv/python3.9/lib/python3.9/site-packages/numba/core/byteflow.py:269

During: resolving callee type: Function(<built-in function arange>)
During: typing of call at /opt/venv/python3.9/lib/python3.9/site-packages/fastdist/fastdist.py (320)

File "../../opt/venv/python3.9/lib/python3.9/site-packages/fastdist/fastdist.py", line 320:
def cosine_pairwise_distance(a, return_matrix=False):
    <source elided>
    n = a.shape[0]
    rows = np.arange(n)
    ^

During: resolving callee type: type(CPUDispatcher(<function cosine_pairwise_distance at 0x7fd0f85dd8b0>))
During: typing of call at /opt/venv/python3.9/lib/python3.9/site-packages/fastdist/fastdist.py (975)

During: resolving callee type: type(CPUDispatcher(<function cosine_pairwise_distance at 0x7fd0f85dd8b0>))
During: typing of call at /opt/venv/python3.9/lib/python3.9/site-packages/fastdist/fastdist.py (975)

File "../../opt/venv/python3.9/lib/python3.9/site-packages/fastdist/fastdist.py", line 975:
def matrix_pairwise_distance(a, metric, metric_name, return_matrix=False):
    <source elided>
    if metric_name == "cosine":
        return cosine_pairwise_distance(a, return_matrix)
###########################################################################################
from fastdist import fastdist
import numpy as np
a = np.random.rand(25, 100)
b = np.random.rand(50, 100)
fastdist.matrix_to_matrix_distance(a, b, fastdist.euclidean, "euclidean")

TypingError                               Traceback (most recent call last)
<ipython-input-3-c80e10b37c18> in <module>
      5 b = np.random.rand(50, 100)
      6 
----> 7 fastdist.matrix_to_matrix_distance(a, b, fastdist.euclidean, "euclidean")
      8 # returns an array of shape (25, 50)

/opt/venv/python3.9/lib/python3.9/site-packages/numba/core/dispatcher.py in _compile_for_args(self, *args, **kws)
    413                 e.patch_message(msg)
    414 
--> 415             error_rewrite(e, 'typing')
    416         except errors.UnsupportedError as e:
    417             # Something unsupported is present in the user code, add help info

/opt/venv/python3.9/lib/python3.9/site-packages/numba/core/dispatcher.py in error_rewrite(e, issue_type)
    356                 raise e
    357             else:
--> 358                 reraise(type(e), e, None)
    359 
    360         argtypes = []

/opt/venv/python3.9/lib/python3.9/site-packages/numba/core/utils.py in reraise(tp, value, tb)
     78         value = tp()
     79     if value.__traceback__ is not tb:
---> 80         raise value.with_traceback(tb)
     81     raise value
     82 

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Failed in nopython mode pipeline (step: nopython frontend)
Internal error at <numba.core.typeinfer.CallConstraint object at 0x7fd0f44248e0>.
Failed in nopython mode pipeline (step: analyzing bytecode)
Use of unsupported opcode (IS_OP) found

File "../../opt/venv/python3.9/lib/python3.9/site-packages/fastdist/fastdist.py", line 23:
def init_w(w, n):
    <source elided>
    """
    if w is None:
    ^

During: resolving callee type: type(CPUDispatcher(<function init_w at 0x7fd11bd73f70>))
During: typing of call at /opt/venv/python3.9/lib/python3.9/site-packages/fastdist/fastdist.py (364)

Enable logging at debug level for details.

File "../../opt/venv/python3.9/lib/python3.9/site-packages/fastdist/fastdist.py", line 364:
def euclidean(u, v, w=None):
    <source elided>
    n = len(u)
    w = init_w(w, n)
    ^

During: resolving callee type: type(CPUDispatcher(<function euclidean at 0x7fd0f85dda60>))
During: typing of call at /opt/venv/python3.9/lib/python3.9/site-packages/fastdist/fastdist.py (985)

During: resolving callee type: type(CPUDispatcher(<function euclidean at 0x7fd0f85dda60>))
During: typing of call at /opt/venv/python3.9/lib/python3.9/site-packages/fastdist/fastdist.py (985)

During: resolving callee type: type(CPUDispatcher(<function euclidean at 0x7fd0f85dda60>))
During: typing of call at /opt/venv/python3.9/lib/python3.9/site-packages/fastdist/fastdist.py (934)

During: resolving callee type: type(CPUDispatcher(<function euclidean at 0x7fd0f85dda60>))
During: typing of call at /opt/venv/python3.9/lib/python3.9/site-packages/fastdist/fastdist.py (934)

File "../../opt/venv/python3.9/lib/python3.9/site-packages/fastdist/fastdist.py", line 934:
def matrix_to_matrix_distance(a, b, metric, metric_name):
    <source elided>
        for j in range(m):
            out[i][j] = metric(a[i], b[j])
            ^

**Comment by talboger** [comment]
Hi,

Unfortunately I'm unable to replicate this error. When I run with the versions you've described, the code compiles with no errors. Perhaps there's something weird with different dependencies? I'll keep looking into it.

Thanks!
