### ISSUE TITLE
[BUG] matrix_to_matrix_distance not working with float32

### ISSUE THREAD

**Issue by vinson2233** [talboger/fastdist#7]
fastdist version : 1.1.2
numba version : 0.53.1
numpy version : 1.19.5

This slightly modified example from the readme
```python
import numpy as np
from fastdist import fastdist
a = np.random.rand(25, 100).astype(np.float32)
b = np.random.rand(50, 100).astype(np.float32)

fastdist.matrix_to_matrix_distance(a, b, fastdist.euclidean, "euclidean")
```
give this error 
```
TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Can't unify return type from the following types: array(float32, 2d, C), array(float64, 2d, C)
Return of: IR name '$18return_value.4', type 'array(float32, 2d, C)', location: 
File "../../opt/conda/lib/python3.7/site-packages/fastdist/fastdist.py", line 931:
def matrix_to_matrix_distance(a, b, metric, metric_name):
    <source elided>
    if metric_name == "cosine":
        return cosine_matrix_to_matrix(a, b)
        ^
Return of: IR name '$120return_value.1', type 'array(float64, 2d, C)', location: 
File "../../opt/conda/lib/python3.7/site-packages/fastdist/fastdist.py", line 937:
def matrix_to_matrix_distance(a, b, metric, metric_name):
    <source elided>
            out[i][j] = metric(a[i], b[j])
    return out
    ^
```

**Comment by vinson2233** [comment]
When I remove these lines from `matrix_to_matrix_distance` function :
```python
if metric_name == "cosine":
        return cosine_matrix_to_matrix(a, b)
```

The `matrix_to_matrix_distance` works as intended on the example above. It seems that some operation in `cosine_matrix_to_matrix` cast the processed value into float64, that's why the numba can't decided to compile the function to return float32 or float64.

**Comment by talboger** [comment]
Hm this is really interesting. It actually seems to b the opposite of what you're describing - if you call `cosine_matrix_to_matrix` on two float32 matrices, it returns a float32 matrix, whereas if you call some other distance function in `matrix_to_matrix_distance`, it returns float64. I'm not quite sure what is causing this, but will look into it - thanks!

**Comment by vinson2233** [comment]
This issues might helps https://github.com/numba/numba/issues/3521

**Comment by talboger** [comment]
Thanks for these links. I've played around with some things and it seems the best "true" way to get rid of this error is by specifying the input/return types in the numba function signature. However, this is then problematic, because if we make this change such that we can accept float32, then float64 won't work. For now, the best thing is probably to just cast your array into a float64 array. I'll try out some new things and re-open the issue if I make any progress
